{"name": "test_register_user_with_first_name_contains_special_characters", "status": "failed", "statusDetails": {"message": "AssertionError: Test Failed! Characters: '!, #, $, %, &, *, /, @, ?, ^, ', :, <, >, ~, {, }, _, +, -, =, |, [, ], (, ), ;, \\, \", `, ,' are not allowed", "trace": "self = <test_cases.test_001_registration_ddt.TestUserRegistration object at 0x00000179FCB2EB10>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f84ac61ae3394bb029df2bab92152091\")>\n\n    def test_register_user_with_first_name_contains_special_characters(self, setup):\n        self.open_register_form(setup)\n        self.logger.info(\"Starting test with first name contains special char\")\n        self.register_page = AccountRegistrationPage(setup)\n        f_name_with_char = [self.username + str(char) for char in self.chars]\n        not_allowed_chars = []\n        for f_name in f_name_with_char:\n            self.username = generate_random_username(7)\n            self.register_page.register(\n                self.username,\n                self.email,\n                self.password,\n                self.conf_password,\n                f_name,\n                self.last_name\n            )\n    \n            try:\n                expected_error_text = \"The name must contains only letters\"\n                error_text = self.register_page.get_error_message()\n                assert error_text.is_displayed()\n                assert error_text.text == expected_error_text\n            except NoSuchElementException:\n                not_allowed_chars.append(f_name[-1])\n                self.my_account_page = MyAccountPage(self.driver)\n                self.my_account_page.click_logout()\n            self.home_page = HomePage(self.driver)\n            self.home_page.click_register()\n    \n        if len(not_allowed_chars) > 0:\n>           raise AssertionError(f\"Test Failed! Characters: '{', '.join(not_allowed_chars)}' are not allowed\")\nE           AssertionError: Test Failed! Characters: '!, #, $, %, &, *, /, @, ?, ^, ', :, <, >, ~, {, }, _, +, -, =, |, [, ], (, ), ;, \\, \", `, ,' are not allowed\n\ntest_cases\\test_001_registration_ddt.py:595: AssertionError"}, "attachments": [{"name": "log", "source": "3c018245-dc52-4acb-bb3f-1542d3a55e66-attachment.txt", "type": "text/plain"}], "start": 1702741033655, "stop": 1702741142597, "uuid": "b01fb011-0d40-41ff-801f-56355631973f", "historyId": "82953a02f747b45cb5fc40177b9748f3", "testCaseId": "82953a02f747b45cb5fc40177b9748f3", "fullName": "test_cases.test_001_registration_ddt.TestUserRegistration#test_register_user_with_first_name_contains_special_characters", "labels": [{"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_001_registration_ddt"}, {"name": "subSuite", "value": "TestUserRegistration"}, {"name": "host", "value": "DESKTOP-53FL5C3"}, {"name": "thread", "value": "15436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_001_registration_ddt"}]}